### ISSUE TITLE
Getting error with settle when opening the landing page on web.

### ISSUE THREAD

**Issue by singlautsav** [satnaing/next-bookstore#16]
` ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⨯ node_modules/axios/lib/core/settle.js (19:11) @ settle
 ⨯ AxiosError: Request failed with status code 404
    at IncomingMessage.emit (node:events:539:35)
null
 ⨯ node_modules/axios/lib/core/settle.js (19:11) @ settle
 ⨯ AxiosError: Request failed with status code 404
    at IncomingMessage.emit (node:events:539:35)
digest: "4256587023"
null
 ⨯ node_modules/axios/lib/core/settle.js (19:11) @ settle
 ⨯ AxiosError: Request failed with status code 404
    at IncomingMessage.emit (node:events:539:35)
null
 ⨯ node_modules/axios/lib/core/settle.js (19:11) @ settle
 ⨯ AxiosError: Request failed with status code 404
    at IncomingMessage.emit (node:events:539:35)
digest: "4256587023"
null`

I am getting this error when I run the frontend code, after setting up strapi and installing every dependancy.

**Comment by petrovicdorde** [comment]
Did you create .env file for frontend?

Here is my:
NEXT_PUBLIC_BACKEND_URL=http://127.0.0.1:1337/api

You can separate route /api if you want, but it doesn't matter.

**Comment by Ndegwadavid** [comment]
Hey!, am also getting an error 
![Screenshot_2024-04-30_14_44_55](https://github.com/satnaing/next-bookstore/assets/107948989/35d10f11-49cf-4f7c-891e-30921cdea9d3)
what exacltly is the APP_KEYS? and how do i fix the error?

**Comment by Ndegwadavid** [comment]
┌──(heffen㉿heffen)-[~/Desktop/next-bookstore-main/backend]
└─$ npm run develop

> backend@0.1.0 develop
> strapi develop

Building your admin UI with development configuration...
Admin UI built successfully
Error: Middleware "strapi::session": App keys are required. Please set app.keys in config/server.js (ex: keys: ['myKeyA', 'myKeyB'])
    at instantiateMiddleware (/home/heffen/Desktop/next-bookstore-main/backend/node_modules/@strapi/strapi/lib/services/server/middleware.js:13:11)
    at resolveMiddlewares (/home/heffen/Desktop/next-bookstore-main/backend/node_modules/@strapi/strapi/lib/services/server/middleware.js:57:18)
    at registerApplicationMiddlewares (/home/heffen/Desktop/next-bookstore-main/backend/node_modules/@strapi/strapi/lib/services/server/register-middlewares.js:66:29)
    at async Object.initMiddlewares (/home/heffen/Desktop/next-bookstore-main/backend/node_modules/@strapi/strapi/lib/services/server/index.js:102:7)
    at async Strapi.bootstrap (/home/heffen/Desktop/next-bookstore-main/backend/node_modules/@strapi/strapi/lib/Strapi.js:478:5)
    at async Strapi.load (/home/heffen/Desktop/next-bookstore-main/backend/node_modules/@strapi/strapi/lib/Strapi.js:492:5)
    at async workerProcess (/home/heffen/Desktop/next-bookstore-main/backend/node_modules/@strapi/strapi/lib/commands/actions/develop/action.js:110:26)
    
    this the error am getting
